In [44]:
#INSTALAR LIBRERIAS
!pip3 install pandas
!pip3 install numpy
!pip3 install matplotlib
!pip3 install seaborn
!pip3 install openpyxl
!pip3 install sympy

In [45]:
#Importamos librerías requeridas 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sympy import primerange

In [46]:
#Convertimos el dataset en dataframe
df= pd.read_csv("los-angeles.csv")
df

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2708,"Run Runyon, Beaut Furn Mirror Mini-Suit w/ Fir...",3008.0,1.462506e+18,⁨Chas.⁩,City of Los Angeles,Hollywood,34.096250,-118.346050,Private room,67.0,30.0,47,2026-05-26,0.32,2.0,301,3,NaN
1,2732,Zen Life at the Beach,3041.0,1.462506e+18,Yogapriestess,Other Cities,Santa Monica,34.004400,-118.480950,Private room,214.0,1.0,24,2022-08-21,0.13,2.0,350,0,228269
2,6033,Poolside Serenity Studio,11619.0,1.462507e+18,Sarah,City of Los Angeles,Woodland Hills,34.168870,-118.644780,Entire home/apt,100.0,30.0,19,2020-03-22,0.09,7.0,270,0,NaN
3,6931,"RUN Runyon, Beau Furn Rms Terrace Hollyw Hill ...",3008.0,1.462506e+18,⁨Chas.⁩,City of Los Angeles,Hollywood,34.096260,-118.343720,Private room,95.0,30.0,39,2025-12-15,0.19,2.0,259,2,NaN
4,7874,HD Wi-Fi E Bellflower Cerritos Lakewood LB LA,21700.0,1.462507e+18,Henry,Other Cities,Bellflower,33.876870,-118.114440,Private room,113.0,1.0,26,2026-04-02,0.29,4.0,103,9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43927,1707678777570851520,The French Lime Pool House - Sleeps 8 - Air ho...,588675098.0,1.463893e+18,Posh,Unincorporated Areas,Desert View Highlands,34.587350,-118.160880,Entire home/apt,220.0,2.0,0,NaN,NaN,13.0,361,0,NaN
43928,1707701464310658544,Hollywood City Views The Godfrey,383724181.0,1.469787e+18,Upscale LA,Other Cities,West Hollywood,34.093596,-118.343729,Entire home/apt,399.0,3.0,0,NaN,NaN,14.0,361,0,Exempt
43929,1707712658970417218,Spacious Waterfront 3BR Marina Retreat,412269286.0,1.469879e+18,Tee,Unincorporated Areas,Marina del Rey,33.976153,-118.452329,Entire home/apt,927.0,14.0,0,NaN,NaN,1.0,365,0,NaN
43930,1707714248958928308,Zen in Hollywood Walk of Fame,383724181.0,1.469787e+18,Upscale LA,Other Cities,West Hollywood,34.093596,-118.343729,Entire home/apt,532.0,1.0,0,NaN,NaN,14.0,361,0,Exempt


In [47]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43932 entries, 0 to 43931
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              43932 non-null  int64  
 1   name                            43932 non-null  str    
 2   host_id                         43751 non-null  float64
 3   host_profile_id                 43537 non-null  float64
 4   host_name                       43548 non-null  str    
 5   neighbourhood_group             43932 non-null  str    
 6   neighbourhood                   43932 non-null  str    
 7   latitude                        43932 non-null  float64
 8   longitude                       43932 non-null  float64
 9   room_type                       43932 non-null  str    
 10  price                           38362 non-null  float64
 11  minimum_nights                  43921 non-null  float64
 12  number_of_reviews               43932 non-n

In [48]:
#Convertimos el DataFrame de pandas en un arreglo de numpy
array = df.to_numpy()
array

array([[2708, 'Run Runyon, Beaut Furn Mirror Mini-Suit w/ Firplc!',
        3008.0, ..., 301, 3, nan],
       [2732, 'Zen Life at the Beach', 3041.0, ..., 350, 0, '228269'],
       [6033, 'Poolside Serenity Studio', 11619.0, ..., 270, 0, nan],
       ...,
       [1707712658970417218, 'Spacious Waterfront 3BR Marina Retreat',
        412269286.0, ..., 365, 0, nan],
       [1707714248958928308, 'Zen in Hollywood Walk of Fame',
        383724181.0, ..., 361, 0, 'Exempt'],
       [1707753561170835767, 'West Hills Oasis', 382786700.0, ..., 363,
        0, nan]], shape=(43932, 19), dtype=object)

In [49]:
# Inciso A
inciso_A = array[:, [1, 4, 9, 10]]
np.savetxt("inciso_A.csv", inciso_A, delimiter=",", fmt="%s", encoding="utf-8")

In [50]:
# Inciso B 
inciso_B = array[:, [1] + list(range(4, 19))]
np.savetxt("inciso_B.csv", inciso_B, delimiter=",", fmt="%s", encoding="utf-8")

In [54]:
# Inciso C
inciso_C = array[[0]+list(range(50, 101))+[200]+[1000]+[2000]+[3000]+[5000]+list(range(7000, 8001)), :]
np.savetxt("inciso_C.csv", inciso_C, delimiter=",", fmt="%s", encoding="utf-8")

In [52]:
# Inciso D
inciso_D = array[::2,1::2]
np.savetxt("inciso_D.csv", inciso_D, delimiter=",", fmt="%s", encoding="utf-8")

In [55]:
# Inciso E
filas_primas = list(primerange(0, array.shape[0]))
columnas_primas = list(primerange(0, 19))

inciso_E = array[filas_primas] [:, columnas_primas]
np.savetxt("inciso_E.csv", inciso_E, delimiter=",", fmt="%s", encoding="utf-8")

***Indexación de un array 1D a partir de un array 2D***

In [ ]:
# Acceder a la primera fila de un arreglo de numpy
fila0 = array[0]
fila0

array([2708, 'Run Runyon, Beaut Furn Mirror Mini-Suit w/ Firplc!', 3008.0,
       1.4625063336794506e+18, '\u2068Chas.\u2069', 'City of Los Angeles',
       'Hollywood', 34.09625, -118.34605, 'Private room', 67.0, 30.0, 47,
       '2026-05-26', 0.32, 2.0, 301, 3, nan], dtype=object)

In [ ]:
# Acceder a la primera fila de un Dataframe de pandas
fila0 = df.iloc[0]
fila0

id                                                                             2708
name                              Run Runyon, Beaut Furn Mirror Mini-Suit w/ Fir...
host_id                                                                      3008.0
host_profile_id                                               1462506333679450624.0
host_name                                                                   ⁨Chas.⁩
neighbourhood_group                                             City of Los Angeles
neighbourhood                                                             Hollywood
latitude                                                                   34.09625
longitude                                                                -118.34605
room_type                                                              Private room
price                                                                          67.0
minimum_nights                                                              

In [ ]:
# Acceder a la primera fila de un arreglo de numpy
# en numpy -> [filas, columnas]
# : significa todas. 

# Ejemplo
columna0 = array[:, 0]
columna0

array([2708, 2732, 6033, ..., 1707712658970417218, 1707714248958928308,
       1707753561170835767], shape=(43932,), dtype=object)

***Indexación de múltiples arrays 1D a partir de un array 2D***

In [ ]:
# Filas consecutivas 3-5 y la columna 4
# Mismo formato de numpy -> [filas, columnas]
Filas_3_a_5= array[3:6, 4]       
Filas_3_a_5

array(['\u2068Chas.\u2069', 'Henry', 'Sherree Strong'], dtype=object)

In [ ]:
# Filas no consecutivas 2, 8, 12 y Todas las columnas
# Mismo formato de numpy -> [filas, columnas]
Filas_3_a_5= array[[2, 8, 12], :]       
Filas_3_a_5

array([[6033, 'Poolside Serenity Studio', 11619.0,
        1.4625066704430886e+18, 'Sarah', 'City of Los Angeles',
        'Woodland Hills', 34.16887, -118.64478, 'Entire home/apt', 100.0,
        30.0, 19, '2020-03-22', 0.09, 7.0, 270, 0, nan],
       [11877, 'Le petit bungalow private entrance + bikes in VB',
        30484.0, 1.4625071306093916e+18, 'Pascalou',
        'City of Los Angeles', 'Venice', 33.99573, -118.47216,
        'Entire home/apt', 115.0, 30.0, 46, '2021-06-01', 0.26, 3.0, 74,
        0, nan],
       [18067, 'Bohemian rustic abode w/ rooftop jacuzzi near SOFI',
        69546.0, 1.4625083136390339e+18, 'Lisa', 'City of Los Angeles',
        'Venice', 33.99117, -118.45159, 'Entire home/apt', 342.0, 2.0,
        75, '2026-05-31', 0.43, 3.0, 64, 4, 'HSR25-003309']], dtype=object)

In [ ]:
# Filas combinadas: Filas: 0, 4-6, 10 con Columna: 4
Filas_0_4_5_6_10= array[[0] + list(range(4, 7)) + [10], 4]       
Filas_0_4_5_6_10


array(['\u2068Chas.\u2069', 'Henry', 'Sherree Strong', 'Wendell',
       'Georgia'], dtype=object)

In [ ]:
# Filas pares y todas las columnas
Filas_pares = array[::2, :]
Filas_pares

array([[2708, 'Run Runyon, Beaut Furn Mirror Mini-Suit w/ Firplc!',
        3008.0, ..., 301, 3, nan],
       [6033, 'Poolside Serenity Studio', 11619.0, ..., 270, 0, nan],
       [7874, 'HD Wi-Fi E Bellflower Cerritos Lakewood LB LA', 21700.0,
        ..., 103, 9, nan],
       ...,
       [1707611435616786731, 'Formosa Viila', 571832314.0, ..., 364, 0,
        'HSR26-000276'],
       [1707701464310658544, 'Hollywood City Views The Godfrey',
        383724181.0, ..., 361, 0, 'Exempt'],
       [1707714248958928308, 'Zen in Hollywood Walk of Fame',
        383724181.0, ..., 361, 0, 'Exempt']],
      shape=(21966, 19), dtype=object)

In [ ]:
# Filas impares y todas las columnas
Filas_impares = array[1::2, :]
Filas_impares

array([[2732, 'Zen Life at the Beach', 3041.0, ..., 350, 0, '228269'],
       [6931, 'RUN Runyon, Beau Furn Rms Terrace Hollyw Hill View',
        3008.0, ..., 259, 2, nan],
       [8021, '5-Star Beverly Hills Suite', 22460.0, ..., 298, 0,
        'HSR24-001423'],
       ...,
       [1707678777570851520,
        'The French Lime Pool House - Sleeps 8 - Air hockey',
        588675098.0, ..., 361, 0, nan],
       [1707712658970417218, 'Spacious Waterfront 3BR Marina Retreat',
        412269286.0, ..., 365, 0, nan],
       [1707753561170835767, 'West Hills Oasis', 382786700.0, ..., 363,
        0, nan]], shape=(21966, 19), dtype=object)

In [ ]:
# Filas primas y todas las columnas
primos = list(primerange(0, 20))
Filas_primas = array[primos, :]
Filas_primas

array([[6033, 'Poolside Serenity Studio', 11619.0,
        1.4625066704430886e+18, 'Sarah', 'City of Los Angeles',
        'Woodland Hills', 34.16887, -118.64478, 'Entire home/apt', 100.0,
        30.0, 19, '2020-03-22', 0.09, 7.0, 270, 0, nan],
       [6931, 'RUN Runyon, Beau Furn Rms Terrace Hollyw Hill View',
        3008.0, 1.4625063336794506e+18, '\u2068Chas.\u2069',
        'City of Los Angeles', 'Hollywood', 34.09626, -118.34372,
        'Private room', 95.0, 30.0, 39, '2025-12-15', 0.19, 2.0, 259, 2,
        nan],
       [8021, '5-Star Beverly Hills Suite', 22460.0,
        1.4625069637736015e+18, 'Sherree Strong', 'City of Los Angeles',
        'Pico-Robertson', 34.06016, -118.37911, 'Private room', 96.0,
        31.0, 238, '2025-04-27', 1.15, 1.0, 298, 0, 'HSR24-001423'],
       [9376, 'Bright Apt, walk to Venice Beach', 30319.0,
        1.4625071283488804e+18, 'Cristina', 'City of Los Angeles',
        'Venice', 33.99782, -118.47698, 'Private room', 199.0, 30.0, 54,
        

In [ ]:
# Convertir un arreglo de numpy a CSV
np.savetxt("datos_numpy.csv", array, delimiter=",", fmt="%s", encoding="utf-8")

In [ ]:
#Convertir un dataframe de pandas a CSV
df.to_csv("datos_pandas.csv")